
FROM mcr.microsoft.com/dotnet/core/runtime:3.0
WORKDIR /usr/local

COPY communication/Agent/bin/Release/netcoreapp3.0/linux-x64/ app/
ADD temp/protobuf/lib/ /usr/lib/
ADD temp/libprotos.so /usr/lib/
ADD CAPI/runtime.sh .
RUN apt-get update && apt-get install --no-install-recommends -y procps
ENTRYPOINT ["bash", "runtime.sh"]
CMD ["127.0.0.1:20000", "1", "0", "100"]